/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import ApiClient from '../ApiClient';
import CategoryLinks from './CategoryLinks';


    

/**
 * The Category model module.
 * @module model/Category
 * @version 1.0
 */
export default class Category  {
    /**
     * Constructs a new "Category".
     * @alias module:model/Category
     * @class
    
     * @param name { String } 
    
     * @param color { String } 
    
     * @param id { String } 
    
     * @param createdAt { Date } 
    
     */
    constructor(
    
        name,
    
        color,
    
        id,
    
        createdAt,
    
    ) {

        this.name = name;
        this.color = color;
        this.icon = null;
        this.id = id;
        this.createdAt = createdAt;
        this.type = null;
        this.links = null;

        this.linksType = CategoryLinks;
    }

    /**
    * Constructs a "Category" from a plain JavaScript object.
    * @param { object } data The plain JavaScript object bearing properties of interest.
    * @param { module:model/Category } type Optional instance to populate.
    * @return { module:model/Category } The populated "Category" instance.
    */
    static constructFromObject(
        data,
        type = Category,
    ) {
        if (data === null) {
            throw new Error('No data to build object');
        }


        let object = new type();

        if (data.hasOwnProperty('name')) {
            object.name = ApiClient.convertToType(data['name'], 'String');
        }
        if (data.hasOwnProperty('color')) {
            object.color = ApiClient.convertToType(data['color'], 'String');
        }
        if (data.hasOwnProperty('icon')) {
            object.icon = ApiClient.convertToType(data['icon'], 'String');
        }
        if (data.hasOwnProperty('id')) {
            object.id = ApiClient.convertToType(data['id'], 'String');
        }
        if (data.hasOwnProperty('createdAt')) {
            object.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
        }
        if (data.hasOwnProperty('type')) {
            object.type = ApiClient.convertToType(data['type'], 'String');
        }
        if (data.hasOwnProperty('_links')) {
            object.links = ApiClient.convertToType(data['_links'], object.linksType);
        }

        return object;

    }

    

}



