/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import ApiClient from '../ApiClient';


    

/**
 * The CheckpointLinksOrganizationIriTemplateMapping model module.
 * @module model/CheckpointLinksOrganizationIriTemplateMapping
 * @version 1.0
 */
export default class CheckpointLinksOrganizationIriTemplateMapping  {
    /**
     * Constructs a new "CheckpointLinksOrganizationIriTemplateMapping".
     * @alias module:model/CheckpointLinksOrganizationIriTemplateMapping
     * @class
    
     */
    constructor(
    
    ) {

        this.organization = null;

    }

    /**
    * Constructs a "CheckpointLinksOrganizationIriTemplateMapping" from a plain JavaScript object.
    * @param { object } data The plain JavaScript object bearing properties of interest.
    * @param { module:model/CheckpointLinksOrganizationIriTemplateMapping } object Optional instance to populate.
    * @return { module:model/CheckpointLinksOrganizationIriTemplateMapping } The populated "CheckpointLinksOrganizationIriTemplateMapping" instance.
    */
    static constructFromData(
        data,
        object = null,
    ) {
        if (data === null) {
            throw new Error('No data to build object');
        }

        if (object === null) {
            object = new CheckpointLinksOrganizationIriTemplateMapping();
        }

        if (data.hasOwnProperty('organization')) {
            object.organization = ApiClient.convertToType(data['organization'], 'String');
        }

        return object;
    }

    

}



