/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import ApiClient from '../ApiClient';




/**
 * The PasswordData model module.
 * @module model/PasswordData
 * @version 1.0
 */
export default class PasswordData  {
    /**
     * Constructs a new "PasswordData".
     * @alias module:model/PasswordData
     * @class

     * @param password { String }

     */
    constructor(

        password,

    ) {

        this.password = password;

    }

    /**
    * Constructs a "PasswordData" from a plain JavaScript object.
    * @param { object } data The plain JavaScript object bearing properties of interest.
    * @param { module:model/PasswordData } object Optional instance to populate.
    * @return { module:model/PasswordData } The populated "PasswordData" instance.
    */
    static constructFromData(
        data,
        object = null,
    ) {
        if (data === null) {
            throw new Error('No data to build object');
        }

        if (object === null) {
            object = new PasswordData();
        }

        if (data.hasOwnProperty('password')) {
            object.password = ApiClient.convertToType(data.password, 'String');
        }

        return object;
    }



}



