/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */


import ApiClient from '../ApiClient';
import Report from './Report';




/**
 * The ReportCollection model module.
 * @module model/ReportCollection
 */
export default class ReportCollection  {
    /**
     * Constructs a new "ReportCollection".
     * @alias module:model/ReportCollection
     * @class

     */
    constructor(

    ) {

        this.items = [];

        this.itemsType = Report;
    }

    /**
    * Constructs a "ReportCollection" from a plain JavaScript object.
    * @param { object } data The plain JavaScript object bearing properties of interest.
    * @param { module:model/ReportCollection } object Optional instance to populate.
    * @return { module:model/ReportCollection } The populated "ReportCollection" instance.
    */
    static constructFromData(
        data,
        object = null,
    ) {
        if (data === null) {
            throw new Error('No data to build object');
        }

        if (object === null) {
            object = new ReportCollection();
        }

        if (data.hasOwnProperty('items')) {
            object.items = ApiClient.convertToType(data.items, [object.itemsType]);
        }

        return object;
    }



}



