/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from '../ApiClient'
import WebhookLinksOrganization from './WebhookLinksOrganization'
import WebhookLinksSelf from './WebhookLinksSelf'

/**
 * The WebhookLinks model module.
 * @module model/WebhookLinks
 */
export default class WebhookLinks {
  /**
     * Constructs a new "WebhookLinks".
     * @alias module:model/WebhookLinks
     * @class

     */
  constructor (

  ) {
    this.self = null
    this.organization = null

    this.selfType = WebhookLinksSelf
    this.organizationType = WebhookLinksOrganization
  }

  /**
    * Constructs a "WebhookLinks" from a plain JavaScript object.
    * @param { object } data The plain JavaScript object bearing properties of interest.
    * @param { module:model/WebhookLinks } object Optional instance to populate.
    * @return { module:model/WebhookLinks } The populated "WebhookLinks" instance.
    */
  static constructFromData (
    data,
    object = null
  ) {
    if (data === null) {
      throw new Error('No data to build object')
    }

    if (object === null) {
      object = new WebhookLinks()
    }

    if (data.hasOwnProperty('self')) {
      object.self = ApiClient.convertToType(data.self, object.selfType)
    }
    if (data.hasOwnProperty('organization')) {
      object.organization = ApiClient.convertToType(data.organization, object.organizationType)
    }

    return object
  }
}
