/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ApiClient from '../ApiClient';
import Error from '../model/Error';
import RefreshToken from '../model/RefreshToken';
import SuccessLogin from '../model/SuccessLogin';

/**
 * Refresh service.
 * @module api/RefreshApi
 * @version 1.0
 */
export default class RefreshApi extends ApiClient {
    /**
     * @class
     * { string } basePath To override basePath.
     * { object } headers Additional headers for the instance.
     * { int } timeout Number in seconds before timeout.
     */
    constructor(
        basePath = null,
        headers = null,
        timeout = null
    ) {
        super(basePath, headers, timeout);
    }

    /**
     * Create one Refresh resource.
     * @param { String } xKeyclicApp 
     * @param { SuccessLogin }  returnType The required type to return; can be a string for simple types or the constructor for a complex type.
     * @param { module:model/String } acceptLanguage   (default to fr-FR)
     * @param { module:model/RefreshToken } refreshToken  
     */
    postRefresh(
        returnType = null,
        options,
    ) {
        if (returnType === null) {
            returnType = SuccessLogin;
        }

        let {
            xKeyclicApp,
            acceptLanguage,
            refreshToken,
        } = options;

        
        // verify the required parameter 'xKeyclicApp' is set
        if (typeof xKeyclicApp === 'undefined' || xKeyclicApp === null) {
            throw new window.Error('Missing the required parameter "xKeyclicApp" when calling postRefresh');
        }
        

        
        // verify the default value of parameter 'acceptLanguage'
        if (typeof acceptLanguage === 'undefined' || acceptLanguage === null) {
            acceptLanguage = "fr-FR";  // eslint-disable-line quotes
        }
        

        
        // verify the null value of parameter 'refreshToken'
        if (typeof refreshToken === 'undefined') {
            refreshToken = null;
        }
        


        let pathParams = {
        };

        let bodyParam = refreshToken;

        let queryParams = {
        };

        let headerParams = {
            'x-keyclic-app': xKeyclicApp,
            'accept-language': acceptLanguage,
        };

        let credentialParams = null;

        let authNames = [
        ];

        let contentTypes = [
            'application/json;charset=UTF-8',
        ];

        let accepts = [
            'application/hal+json;charset=UTF-8',
        ];

        return this.callApi(
            '/security/login/refresh',
            'POST',
            pathParams,
            queryParams,
            headerParams,
            bodyParam,
            authNames,
            credentialParams,
            contentTypes,
            accepts,
            returnType
        );
    }

}
