/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The About model module.
 * @module model/About
 */
export default class About {
  /**
     * Constructs a new "About".
     * @alias module:model/About
     * @class
    
     */
  constructor() {
    this.name = null;
    this.text = null;
  }

  /**
   * Constructs a "About" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/About } object Optional instance to populate.
   * @return { module:model/About } The populated "About" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new About();
    }

    if (data.hasOwnProperty("name")) {
      object.name = ApiClient.convertToType(data["name"], "String");
    }
    if (data.hasOwnProperty("text")) {
      object.text = ApiClient.convertToType(data["text"], "String");
    }

    return object;
  }

  /**
   * @return { String }
   */
  getName() {
    return this.name;
  }

  /**
   * @param { String } name
   */
  setName(name) {
    this.name = name;
  }
  /**
   * @return { String }
   */
  getText() {
    return this.text;
  }

  /**
   * @param { String } text
   */
  setText(text) {
    this.text = text;
  }
}
