/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import ActivityEntity from "./ActivityEntity";

/**
 * The Activity model module.
 * @module model/Activity
 */
export default class Activity {
  /**
     * Constructs a new "Activity".
     * @alias module:model/Activity
     * @class
    
     */
  constructor() {
    this.actor = null;
    this.message = null;
    this._object = null;
    this.origin = null;
    this.subject = null;
    this.time = null;
    this.title = null;
    this.verb = null;

    this.subjectType = ActivityEntity;
  }

  /**
   * Constructs a "Activity" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/Activity } object Optional instance to populate.
   * @return { module:model/Activity } The populated "Activity" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new Activity();
    }

    if (data.hasOwnProperty("actor")) {
      object.actor = ApiClient.convertToType(data["actor"], "String");
    }
    if (data.hasOwnProperty("message")) {
      object.message = ApiClient.convertToType(data["message"], "String");
    }
    if (data.hasOwnProperty("object")) {
      object._object = ApiClient.convertToType(data["object"], "String");
    }
    if (data.hasOwnProperty("origin")) {
      object.origin = ApiClient.convertToType(data["origin"], "String");
    }
    if (data.hasOwnProperty("subject")) {
      object.subject = ApiClient.convertToType(
        data["subject"],
        object.subjectType
      );
    }
    if (data.hasOwnProperty("time")) {
      object.time = ApiClient.convertToType(data["time"], "Date");
    }
    if (data.hasOwnProperty("title")) {
      object.title = ApiClient.convertToType(data["title"], "String");
    }
    if (data.hasOwnProperty("verb")) {
      object.verb = ApiClient.convertToType(data["verb"], "String");
    }

    return object;
  }

  /**
   * @return { String }
   */
  getActor() {
    return this.actor;
  }

  /**
   * @param { String } actor
   */
  setActor(actor) {
    this.actor = actor;
  }
  /**
   * @return { String }
   */
  getMessage() {
    return this.message;
  }

  /**
   * @param { String } message
   */
  setMessage(message) {
    this.message = message;
  }
  /**
   * @return { String }
   */
  getObject() {
    return this._object;
  }

  /**
   * @param { String } _object
   */
  setObject(_object) {
    this._object = _object;
  }
  /**
   * @return { String }
   */
  getOrigin() {
    return this.origin;
  }

  /**
   * @param { String } origin
   */
  setOrigin(origin) {
    this.origin = origin;
  }
  /**
   * @return { module:model/ActivityEntity }
   */
  getSubject() {
    return this.subject;
  }

  /**
   * @param { module:model/ActivityEntity } subject
   */
  setSubject(subject) {
    this.subject = subject;
  }
  /**
   * @return { Date }
   */
  getTime() {
    return this.time;
  }

  /**
   * @param { Date } time
   */
  setTime(time) {
    this.time = time;
  }
  /**
   * @return { String }
   */
  getTitle() {
    return this.title;
  }

  /**
   * @param { String } title
   */
  setTitle(title) {
    this.title = title;
  }
  /**
   * @return { String }
   */
  getVerb() {
    return this.verb;
  }

  /**
   * @param { String } verb
   */
  setVerb(verb) {
    this.verb = verb;
  }
}
