/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import Article from "./Article";

/**
 * The ArticleCollection model module.
 * @module model/ArticleCollection
 */
export default class ArticleCollection {
  /**
     * Constructs a new "ArticleCollection".
     * @alias module:model/ArticleCollection
     * @class
    
     */
  constructor() {
    this.items = [];

    this.itemsType = Article;
  }

  /**
   * Constructs a "ArticleCollection" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ArticleCollection } object Optional instance to populate.
   * @return { module:model/ArticleCollection } The populated "ArticleCollection" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ArticleCollection();
    }

    if (data.hasOwnProperty("items")) {
      object.items = ApiClient.convertToType(data["items"], [object.itemsType]);
    }

    return object;
  }

  /**
   * @return { Array.<module:model/Article> }
   */
  getItems() {
    return this.items;
  }

  /**
   * @param { Array.<module:model/Article> } items
   */
  setItems(items) {
    this.items = items;
  }
}
