/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import Contribution from "./Contribution";

/**
 * The ContributionCollection model module.
 * @module model/ContributionCollection
 */
export default class ContributionCollection {
  /**
     * Constructs a new "ContributionCollection".
     * @alias module:model/ContributionCollection
     * @class
    
     */
  constructor() {
    this.items = [];

    this.itemsType = Contribution;
  }

  /**
   * Constructs a "ContributionCollection" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ContributionCollection } object Optional instance to populate.
   * @return { module:model/ContributionCollection } The populated "ContributionCollection" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ContributionCollection();
    }

    if (data.hasOwnProperty("items")) {
      object.items = ApiClient.convertToType(data["items"], [object.itemsType]);
    }

    return object;
  }

  /**
   * @return { Array.<module:model/Contribution> }
   */
  getItems() {
    return this.items;
  }

  /**
   * @param { Array.<module:model/Contribution> } items
   */
  setItems(items) {
    this.items = items;
  }
}
