/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import ContributionLinksContributor from "./ContributionLinksContributor";
import ContributionLinksFeedback from "./ContributionLinksFeedback";

/**
 * The ContributionLinks model module.
 * @module model/ContributionLinks
 */
export default class ContributionLinks {
  /**
     * Constructs a new "ContributionLinks".
     * @alias module:model/ContributionLinks
     * @class
    
     */
  constructor() {
    this.contributor = null;
    this.feedback = null;

    this.contributorType = ContributionLinksContributor;
    this.feedbackType = ContributionLinksFeedback;
  }

  /**
   * Constructs a "ContributionLinks" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ContributionLinks } object Optional instance to populate.
   * @return { module:model/ContributionLinks } The populated "ContributionLinks" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ContributionLinks();
    }

    if (data.hasOwnProperty("contributor")) {
      object.contributor = ApiClient.convertToType(
        data["contributor"],
        object.contributorType
      );
    }
    if (data.hasOwnProperty("feedback")) {
      object.feedback = ApiClient.convertToType(
        data["feedback"],
        object.feedbackType
      );
    }

    return object;
  }
}
