/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The ContributionLinksFeedbackIriTemplateMapping model module.
 * @module model/ContributionLinksFeedbackIriTemplateMapping
 */
export default class ContributionLinksFeedbackIriTemplateMapping {
  /**
     * Constructs a new "ContributionLinksFeedbackIriTemplateMapping".
     * @alias module:model/ContributionLinksFeedbackIriTemplateMapping
     * @class
    
     */
  constructor() {
    this.feedback = null;
  }

  /**
   * Constructs a "ContributionLinksFeedbackIriTemplateMapping" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ContributionLinksFeedbackIriTemplateMapping } object Optional instance to populate.
   * @return { module:model/ContributionLinksFeedbackIriTemplateMapping } The populated "ContributionLinksFeedbackIriTemplateMapping" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ContributionLinksFeedbackIriTemplateMapping();
    }

    if (data.hasOwnProperty("feedback")) {
      object.feedback = ApiClient.convertToType(data["feedback"], "String");
    }

    return object;
  }

  /**
   * @return { String }
   */
  getFeedback() {
    return this.feedback;
  }

  /**
   * @param { String } feedback
   */
  setFeedback(feedback) {
    this.feedback = feedback;
  }
}
