/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import DocumentPatchFile from "./DocumentPatchFile";
import DocumentPermission from "./DocumentPermission";

/**
 * The DocumentPatch model module.
 * @module model/DocumentPatch
 */
export default class DocumentPatch {
  /**
     * Constructs a new "DocumentPatch".
     * @alias module:model/DocumentPatch
     * @class
    
     */
  constructor() {
    this.file = null;
    this.permission = null;

    this.fileType = DocumentPatchFile;
    this.permissionType = DocumentPermission;
  }

  /**
   * Constructs a "DocumentPatch" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/DocumentPatch } object Optional instance to populate.
   * @return { module:model/DocumentPatch } The populated "DocumentPatch" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new DocumentPatch();
    }

    if (data.hasOwnProperty("file")) {
      object.file = ApiClient.convertToType(data["file"], object.fileType);
    }
    if (data.hasOwnProperty("permission")) {
      object.permission = ApiClient.convertToType(
        data["permission"],
        object.permissionType
      );
    }

    return object;
  }
}
