/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The Duration model module.
 * @module model/Duration
 */
export default class Duration {
  /**
     * Constructs a new "Duration".
     * @alias module:model/Duration
     * @class
    
     */
  constructor() {
    this.hours = null;
    this.minutes = null;
    this.seconds = null;
  }

  /**
   * Constructs a "Duration" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/Duration } object Optional instance to populate.
   * @return { module:model/Duration } The populated "Duration" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new Duration();
    }

    if (data.hasOwnProperty("hours")) {
      object.hours = ApiClient.convertToType(data["hours"], "Number");
    }
    if (data.hasOwnProperty("minutes")) {
      object.minutes = ApiClient.convertToType(data["minutes"], "Number");
    }
    if (data.hasOwnProperty("seconds")) {
      object.seconds = ApiClient.convertToType(data["seconds"], "Number");
    }

    return object;
  }

  /**
   * @return { Number }
   */
  getHours() {
    return this.hours;
  }

  /**
   * @param { Number } hours
   */
  setHours(hours) {
    this.hours = hours;
  }
  /**
   * @return { Number }
   */
  getMinutes() {
    return this.minutes;
  }

  /**
   * @param { Number } minutes
   */
  setMinutes(minutes) {
    this.minutes = minutes;
  }
  /**
   * @return { Number }
   */
  getSeconds() {
    return this.seconds;
  }

  /**
   * @param { Number } seconds
   */
  setSeconds(seconds) {
    this.seconds = seconds;
  }
}
