/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import FeatureGeometry from "./FeatureGeometry";

/**
 * The Feature model module.
 * @module model/Feature
 */
export default class Feature {
  /**
     * Constructs a new "Feature".
     * @alias module:model/Feature
     * @class
    
     */
  constructor() {
    this.type = "Feature";
    this.geometry = null;
    this.properties = [];

    this.geometryType = FeatureGeometry;
  }

  /**
   * Constructs a "Feature" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/Feature } object Optional instance to populate.
   * @return { module:model/Feature } The populated "Feature" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new Feature();
    }

    if (data.hasOwnProperty("type")) {
      object.type = ApiClient.convertToType(data["type"], "String");
    }
    if (data.hasOwnProperty("geometry")) {
      object.geometry = ApiClient.convertToType(
        data["geometry"],
        object.geometryType
      );
    }
    if (data.hasOwnProperty("properties")) {
      object.properties = ApiClient.convertToType(
        data["properties"],
        "['String']"
      );
    }

    return object;
  }
}
