/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import FeedbackReviewRequest from "./FeedbackReviewRequest";

/**
 * The FeedbackReviewRequestCollection model module.
 * @module model/FeedbackReviewRequestCollection
 */
export default class FeedbackReviewRequestCollection {
  /**
     * Constructs a new "FeedbackReviewRequestCollection".
     * @alias module:model/FeedbackReviewRequestCollection
     * @class
    
     */
  constructor() {
    this.items = [];

    this.itemsType = FeedbackReviewRequest;
  }

  /**
   * Constructs a "FeedbackReviewRequestCollection" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/FeedbackReviewRequestCollection } object Optional instance to populate.
   * @return { module:model/FeedbackReviewRequestCollection } The populated "FeedbackReviewRequestCollection" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new FeedbackReviewRequestCollection();
    }

    if (data.hasOwnProperty("items")) {
      object.items = ApiClient.convertToType(data["items"], [object.itemsType]);
    }

    return object;
  }
}
