/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import InternalServiceLinksOrganization from "./InternalServiceLinksOrganization";
import InternalServiceLinksSelf from "./InternalServiceLinksSelf";

/**
 * The InternalServiceLinks model module.
 * @module model/InternalServiceLinks
 */
export default class InternalServiceLinks {
  /**
     * Constructs a new "InternalServiceLinks".
     * @alias module:model/InternalServiceLinks
     * @class
    
     */
  constructor() {
    this.organization = null;
    this.self = null;

    this.organizationType = InternalServiceLinksOrganization;
    this.selfType = InternalServiceLinksSelf;
  }

  /**
   * Constructs a "InternalServiceLinks" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/InternalServiceLinks } object Optional instance to populate.
   * @return { module:model/InternalServiceLinks } The populated "InternalServiceLinks" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new InternalServiceLinks();
    }

    if (data.hasOwnProperty("organization")) {
      object.organization = ApiClient.convertToType(
        data["organization"],
        object.organizationType
      );
    }
    if (data.hasOwnProperty("self")) {
      object.self = ApiClient.convertToType(data["self"], object.selfType);
    }

    return object;
  }

  /**
   * @return { module:model/InternalServiceLinksOrganization }
   */
  getOrganization() {
    return this.organization;
  }

  /**
   * @param { module:model/InternalServiceLinksOrganization } organization
   */
  setOrganization(organization) {
    this.organization = organization;
  }
  /**
   * @return { module:model/InternalServiceLinksSelf }
   */
  getSelf() {
    return this.self;
  }

  /**
   * @param { module:model/InternalServiceLinksSelf } self
   */
  setSelf(self) {
    this.self = self;
  }
}
