/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import InvitationLinksSelfIriTemplateMapping from "./InvitationLinksSelfIriTemplateMapping";

/**
 * The InvitationLinksSelfIriTemplate model module.
 * @module model/InvitationLinksSelfIriTemplate
 */
export default class InvitationLinksSelfIriTemplate {
  /**
     * Constructs a new "InvitationLinksSelfIriTemplate".
     * @alias module:model/InvitationLinksSelfIriTemplate
     * @class
    
     */
  constructor() {
    this.mapping = null;

    this.mappingType = InvitationLinksSelfIriTemplateMapping;
  }

  /**
   * Constructs a "InvitationLinksSelfIriTemplate" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/InvitationLinksSelfIriTemplate } object Optional instance to populate.
   * @return { module:model/InvitationLinksSelfIriTemplate } The populated "InvitationLinksSelfIriTemplate" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new InvitationLinksSelfIriTemplate();
    }

    if (data.hasOwnProperty("mapping")) {
      object.mapping = ApiClient.convertToType(
        data["mapping"],
        object.mappingType
      );
    }

    return object;
  }

  /**
   * @return { module:model/InvitationLinksSelfIriTemplateMapping }
   */
  getMapping() {
    return this.mapping;
  }

  /**
   * @param { module:model/InvitationLinksSelfIriTemplateMapping } mapping
   */
  setMapping(mapping) {
    this.mapping = mapping;
  }
}
