/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The MemberContactPoint model module.
 * @module model/MemberContactPoint
 */
export default class MemberContactPoint {
  /**
     * Constructs a new "MemberContactPoint".
     * @alias module:model/MemberContactPoint
     * @class
    
     */
  constructor() {
    this.email = null;
    this.name = null;
    this.telephone = null;
  }

  /**
   * Constructs a "MemberContactPoint" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/MemberContactPoint } object Optional instance to populate.
   * @return { module:model/MemberContactPoint } The populated "MemberContactPoint" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new MemberContactPoint();
    }

    if (data.hasOwnProperty("email")) {
      object.email = ApiClient.convertToType(data["email"], "String");
    }
    if (data.hasOwnProperty("name")) {
      object.name = ApiClient.convertToType(data["name"], "String");
    }
    if (data.hasOwnProperty("telephone")) {
      object.telephone = ApiClient.convertToType(data["telephone"], "String");
    }

    return object;
  }

  /**
   * @return { String }
   */
  getEmail() {
    return this.email;
  }

  /**
   * @param { String } email
   */
  setEmail(email) {
    this.email = email;
  }
  /**
   * @return { String }
   */
  getName() {
    return this.name;
  }

  /**
   * @param { String } name
   */
  setName(name) {
    this.name = name;
  }
  /**
   * @return { String }
   */
  getTelephone() {
    return this.telephone;
  }

  /**
   * @param { String } telephone
   */
  setTelephone(telephone) {
    this.telephone = telephone;
  }
}
