/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The OccupantData model module.
 * @module model/OccupantData
 */
export default class OccupantData {
  /**
     * Constructs a new "OccupantData".
     * @alias module:model/OccupantData
     * @class
    
     * @param member { String }
    
     * @param place { String }
    
     */
  constructor(
    member,

    place
  ) {
    this.member = member;
    this.place = place;
  }

  /**
   * Constructs a "OccupantData" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/OccupantData } object Optional instance to populate.
   * @return { module:model/OccupantData } The populated "OccupantData" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new OccupantData();
    }

    if (data.hasOwnProperty("member")) {
      object.member = ApiClient.convertToType(data["member"], "String");
    }
    if (data.hasOwnProperty("place")) {
      object.place = ApiClient.convertToType(data["place"], "String");
    }

    return object;
  }

  /**
   * @return { String }
   */
  getMember() {
    return this.member;
  }

  /**
   * @param { String } member
   */
  setMember(member) {
    this.member = member;
  }
  /**
   * @return { String }
   */
  getPlace() {
    return this.place;
  }

  /**
   * @param { String } place
   */
  setPlace(place) {
    this.place = place;
  }
}
