/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import Member from "./Member";

/**
 * The OccupantEmbedded model module.
 * @module model/OccupantEmbedded
 */
export default class OccupantEmbedded {
  /**
     * Constructs a new "OccupantEmbedded".
     * @alias module:model/OccupantEmbedded
     * @class
    
     */
  constructor() {
    this.member = null;

    this.memberType = Member;
  }

  /**
   * Constructs a "OccupantEmbedded" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/OccupantEmbedded } object Optional instance to populate.
   * @return { module:model/OccupantEmbedded } The populated "OccupantEmbedded" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new OccupantEmbedded();
    }

    if (data.hasOwnProperty("member")) {
      object.member = ApiClient.convertToType(
        data["member"],
        object.memberType
      );
    }

    return object;
  }

  /**
   * @return { module:model/Member }
   */
  getMember() {
    return this.member;
  }

  /**
   * @param { module:model/Member } member
   */
  setMember(member) {
    this.member = member;
  }
}
