/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import OperationLinksOrganizationIriTemplate from "./OperationLinksOrganizationIriTemplate";

/**
 * The OperationLinksOrganization model module.
 * @module model/OperationLinksOrganization
 */
export default class OperationLinksOrganization {
  /**
     * Constructs a new "OperationLinksOrganization".
     * @alias module:model/OperationLinksOrganization
     * @class
    
     */
  constructor() {
    this.href = null;
    this.iriTemplate = null;

    this.iriTemplateType = OperationLinksOrganizationIriTemplate;
  }

  /**
   * Constructs a "OperationLinksOrganization" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/OperationLinksOrganization } object Optional instance to populate.
   * @return { module:model/OperationLinksOrganization } The populated "OperationLinksOrganization" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new OperationLinksOrganization();
    }

    if (data.hasOwnProperty("href")) {
      object.href = ApiClient.convertToType(data["href"], "String");
    }
    if (data.hasOwnProperty("iriTemplate")) {
      object.iriTemplate = ApiClient.convertToType(
        data["iriTemplate"],
        object.iriTemplateType
      );
    }

    return object;
  }

  /**
   * Gets The URI of the organization associated to the given operation.
   * @return { String }
   */
  getHref() {
    return this.href;
  }

  /**
   * Sets The URI of the organization associated to the given operation.
   * @param { String } href The URI of the organization associated to the given operation.
   */
  setHref(href) {
    this.href = href;
  }
  /**
   * @return { module:model/OperationLinksOrganizationIriTemplate }
   */
  getIriTemplate() {
    return this.iriTemplate;
  }

  /**
   * @param { module:model/OperationLinksOrganizationIriTemplate } iriTemplate
   */
  setIriTemplate(iriTemplate) {
    this.iriTemplate = iriTemplate;
  }
}
