/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import OperationSignatureSigner from "./OperationSignatureSigner";

/**
 * The OperationSignature model module.
 * @module model/OperationSignature
 */
export default class OperationSignature {
  /**
     * Constructs a new "OperationSignature".
     * @alias module:model/OperationSignature
     * @class
    
     * @param signer { module:model/OperationSignatureSigner }
    
     * @param signedAt { Date }
    
     */
  constructor(
    signer,

    signedAt
  ) {
    this.signer = signer;
    this.signedAt = signedAt;

    this.signerType = OperationSignatureSigner;
  }

  /**
   * Constructs a "OperationSignature" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/OperationSignature } object Optional instance to populate.
   * @return { module:model/OperationSignature } The populated "OperationSignature" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new OperationSignature();
    }

    if (data.hasOwnProperty("signer")) {
      object.signer = ApiClient.convertToType(
        data["signer"],
        object.signerType
      );
    }
    if (data.hasOwnProperty("signedAt")) {
      object.signedAt = ApiClient.convertToType(data["signedAt"], "Date");
    }

    return object;
  }
}
