/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import PreferencesNotification from "./PreferencesNotification";
import PreferencesReference from "./PreferencesReference";

/**
 * The OrganizationPreferences model module.
 * @module model/OrganizationPreferences
 */
export default class OrganizationPreferences {
  /**
     * Constructs a new "OrganizationPreferences".
     * @alias module:model/OrganizationPreferences
     * @class
    
     */
  constructor() {
    this.categoryRequired = null;
    this.notification = null;
    this.offline = null;
    this._public = null;
    this.reference = null;
    this.reviewEnabled = null;

    this.notificationType = PreferencesNotification;
    this.referenceType = PreferencesReference;
  }

  /**
   * Constructs a "OrganizationPreferences" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/OrganizationPreferences } object Optional instance to populate.
   * @return { module:model/OrganizationPreferences } The populated "OrganizationPreferences" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new OrganizationPreferences();
    }

    if (data.hasOwnProperty("categoryRequired")) {
      object.categoryRequired = ApiClient.convertToType(
        data["categoryRequired"],
        "Boolean"
      );
    }
    if (data.hasOwnProperty("notification")) {
      object.notification = ApiClient.convertToType(
        data["notification"],
        object.notificationType
      );
    }
    if (data.hasOwnProperty("offline")) {
      object.offline = ApiClient.convertToType(data["offline"], "Boolean");
    }
    if (data.hasOwnProperty("public")) {
      object._public = ApiClient.convertToType(data["public"], "Boolean");
    }
    if (data.hasOwnProperty("reference")) {
      object.reference = ApiClient.convertToType(
        data["reference"],
        object.referenceType
      );
    }
    if (data.hasOwnProperty("reviewEnabled")) {
      object.reviewEnabled = ApiClient.convertToType(
        data["reviewEnabled"],
        "Boolean"
      );
    }

    return object;
  }

  /**
   * @return { Boolean }
   */
  getCategoryRequired() {
    return this.categoryRequired;
  }

  /**
   * @param { Boolean } categoryRequired
   */
  setCategoryRequired(categoryRequired) {
    this.categoryRequired = categoryRequired;
  }
  /**
   * @return { module:model/PreferencesNotification }
   */
  getNotification() {
    return this.notification;
  }

  /**
   * @param { module:model/PreferencesNotification } notification
   */
  setNotification(notification) {
    this.notification = notification;
  }
  /**
   * @return { Boolean }
   */
  getOffline() {
    return this.offline;
  }

  /**
   * @param { Boolean } offline
   */
  setOffline(offline) {
    this.offline = offline;
  }
  /**
   * @return { Boolean }
   */
  getPublic() {
    return this._public;
  }

  /**
   * @param { Boolean } _public
   */
  setPublic(_public) {
    this._public = _public;
  }
  /**
   * @return { module:model/PreferencesReference }
   */
  getReference() {
    return this.reference;
  }

  /**
   * @param { module:model/PreferencesReference } reference
   */
  setReference(reference) {
    this.reference = reference;
  }
  /**
   * @return { Boolean }
   */
  getReviewEnabled() {
    return this.reviewEnabled;
  }

  /**
   * @param { Boolean } reviewEnabled
   */
  setReviewEnabled(reviewEnabled) {
    this.reviewEnabled = reviewEnabled;
  }
}
