/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import Feature from "./Feature";

/**
 * The Polygon model module.
 * @module model/Polygon
 */
export default class Polygon {
  /**
     * Constructs a new "Polygon".
     * @alias module:model/Polygon
     * @class
    
     */
  constructor() {
    this.type = "FeatureCollection";
    this.features = [];

    this.featuresType = Feature;
  }

  /**
   * Constructs a "Polygon" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/Polygon } object Optional instance to populate.
   * @return { module:model/Polygon } The populated "Polygon" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new Polygon();
    }

    if (data.hasOwnProperty("type")) {
      object.type = ApiClient.convertToType(data["type"], "String");
    }
    if (data.hasOwnProperty("features")) {
      object.features = ApiClient.convertToType(data["features"], [
        object.featuresType
      ]);
    }

    return object;
  }

  /**
   * @return { String }
   */
  getType() {
    return this.type;
  }

  /**
   * @param { String } type
   */
  setType(type) {
    this.type = type;
  }
  /**
   * @return { Array.<module:model/Feature> }
   */
  getFeatures() {
    return this.features;
  }

  /**
   * @param { Array.<module:model/Feature> } features
   */
  setFeatures(features) {
    this.features = features;
  }
}
