/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The ReportEmbeddedTargetGroups model module.
 * @module model/ReportEmbeddedTargetGroups
 */
export default class ReportEmbeddedTargetGroups {
  /**
     * Constructs a new "ReportEmbeddedTargetGroups".
     * @alias module:model/ReportEmbeddedTargetGroups
     * @class
    
     */
  constructor() {
    this.id = null;
    this.name = null;
    this.description = null;
  }

  /**
   * Constructs a "ReportEmbeddedTargetGroups" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ReportEmbeddedTargetGroups } object Optional instance to populate.
   * @return { module:model/ReportEmbeddedTargetGroups } The populated "ReportEmbeddedTargetGroups" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ReportEmbeddedTargetGroups();
    }

    if (data.hasOwnProperty("id")) {
      object.id = ApiClient.convertToType(data["id"], "String");
    }
    if (data.hasOwnProperty("name")) {
      object.name = ApiClient.convertToType(data["name"], "String");
    }
    if (data.hasOwnProperty("description")) {
      object.description = ApiClient.convertToType(
        data["description"],
        "String"
      );
    }

    return object;
  }

  /**
   * @return { String }
   */
  getId() {
    return this.id;
  }

  /**
   * @param { String } id
   */
  setId(id) {
    this.id = id;
  }
  /**
   * @return { String }
   */
  getName() {
    return this.name;
  }

  /**
   * @param { String } name
   */
  setName(name) {
    this.name = name;
  }
  /**
   * @return { String }
   */
  getDescription() {
    return this.description;
  }

  /**
   * @param { String } description
   */
  setDescription(description) {
    this.description = description;
  }
}
