/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import CategoryLinksSelfIriTemplateMapping from "./CategoryLinksSelfIriTemplateMapping";

/**
 * The ReportLinksCategoryIriTemplate model module.
 * @module model/ReportLinksCategoryIriTemplate
 */
export default class ReportLinksCategoryIriTemplate {
  /**
     * Constructs a new "ReportLinksCategoryIriTemplate".
     * @alias module:model/ReportLinksCategoryIriTemplate
     * @class
    
     */
  constructor() {
    this.mapping = null;

    this.mappingType = CategoryLinksSelfIriTemplateMapping;
  }

  /**
   * Constructs a "ReportLinksCategoryIriTemplate" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ReportLinksCategoryIriTemplate } object Optional instance to populate.
   * @return { module:model/ReportLinksCategoryIriTemplate } The populated "ReportLinksCategoryIriTemplate" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ReportLinksCategoryIriTemplate();
    }

    if (data.hasOwnProperty("mapping")) {
      object.mapping = ApiClient.convertToType(
        data["mapping"],
        object.mappingType
      );
    }

    return object;
  }
}
