/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The ReportPatch model module.
 * @module model/ReportPatch
 */
export default class ReportPatch {
  /**
     * Constructs a new "ReportPatch".
     * @alias module:model/ReportPatch
     * @class
    
     */
  constructor() {
    this.category = null;
    this.description = null;
    this.dueDate = null;
    this.identificationNumber = null;
    this.priority = null;
    this.tags = [];
  }

  /**
   * Constructs a "ReportPatch" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ReportPatch } object Optional instance to populate.
   * @return { module:model/ReportPatch } The populated "ReportPatch" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ReportPatch();
    }

    if (data.hasOwnProperty("category")) {
      object.category = ApiClient.convertToType(data["category"], "String");
    }
    if (data.hasOwnProperty("description")) {
      object.description = ApiClient.convertToType(
        data["description"],
        "String"
      );
    }
    if (data.hasOwnProperty("dueDate")) {
      object.dueDate = ApiClient.convertToType(data["dueDate"], "Date");
    }
    if (data.hasOwnProperty("identificationNumber")) {
      object.identificationNumber = ApiClient.convertToType(
        data["identificationNumber"],
        "String"
      );
    }
    if (data.hasOwnProperty("priority")) {
      object.priority = ApiClient.convertToType(data["priority"], "Number");
    }
    if (data.hasOwnProperty("tags")) {
      object.tags = ApiClient.convertToType(data["tags"], "['String']");
    }

    return object;
  }

  /**
   * @return { String }
   */
  getCategory() {
    return this.category;
  }

  /**
   * @param { String } category
   */
  setCategory(category) {
    this.category = category;
  }
  /**
   * @return { String }
   */
  getDescription() {
    return this.description;
  }

  /**
   * @param { String } description
   */
  setDescription(description) {
    this.description = description;
  }
  /**
   * @return { Date }
   */
  getDueDate() {
    return this.dueDate;
  }

  /**
   * @param { Date } dueDate
   */
  setDueDate(dueDate) {
    this.dueDate = dueDate;
  }
  /**
   * @return { String }
   */
  getIdentificationNumber() {
    return this.identificationNumber;
  }

  /**
   * @param { String } identificationNumber
   */
  setIdentificationNumber(identificationNumber) {
    this.identificationNumber = identificationNumber;
  }
  /**
   * @return { Number }
   */
  getPriority() {
    return this.priority;
  }

  /**
   * @param { Number } priority
   */
  setPriority(priority) {
    this.priority = priority;
  }
  /**
   * @return { Array.<String> }
   */
  getTags() {
    return this.tags;
  }

  /**
   * @param { Array.<String> } tags
   */
  setTags(tags) {
    this.tags = tags;
  }
}
