/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";
import Review from "./Review";

/**
 * The ReviewRequestEmbedded model module.
 * @module model/ReviewRequestEmbedded
 */
export default class ReviewRequestEmbedded {
  /**
     * Constructs a new "ReviewRequestEmbedded".
     * @alias module:model/ReviewRequestEmbedded
     * @class
    
     */
  constructor() {
    this.review = null;

    this.reviewType = Review;
  }

  /**
   * Constructs a "ReviewRequestEmbedded" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/ReviewRequestEmbedded } object Optional instance to populate.
   * @return { module:model/ReviewRequestEmbedded } The populated "ReviewRequestEmbedded" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new ReviewRequestEmbedded();
    }

    if (data.hasOwnProperty("review")) {
      object.review = ApiClient.convertToType(
        data["review"],
        object.reviewType
      );
    }

    return object;
  }

  /**
   * @return { module:model/Review }
   */
  getReview() {
    return this.review;
  }

  /**
   * @param { module:model/Review } review
   */
  setReview(review) {
    this.review = review;
  }
}
