/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *  <techies@keyclic.com>
 *
 * This class is auto generated by the swagger code generator program with proper templates of Keyclic.
 * https://github.com/swagger-api/swagger-codegen.git
 * https://github.com/Keyclic/app-sdk.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

/**
 * The WebhookData model module.
 * @module model/WebhookData
 */
export default class WebhookData {
  /**
     * Constructs a new "WebhookData".
     * @alias module:model/WebhookData
     * @class
    
     * @param event { module:model/WebhookData.EventEnum }
    
     * @param organization { String }
    
     * @param payloadUrl { String }
    
     */
  constructor(
    event,

    organization,

    payloadUrl
  ) {
    this.event = event;
    this.organization = organization;
    this.payloadUrl = payloadUrl;
  }

  /**
   * Constructs a "WebhookData" from a plain JavaScript object.
   * @param { object } data The plain JavaScript object bearing properties of interest.
   * @param { module:model/WebhookData } object Optional instance to populate.
   * @return { module:model/WebhookData } The populated "WebhookData" instance.
   */
  static constructFromData(data, object = null) {
    if (data === null) {
      throw new Error("No data to build object");
    }

    if (object === null) {
      object = new WebhookData();
    }

    if (data.hasOwnProperty("event")) {
      object.event = ApiClient.convertToType(data["event"], "String");
    }
    if (data.hasOwnProperty("organization")) {
      object.organization = ApiClient.convertToType(
        data["organization"],
        "String"
      );
    }
    if (data.hasOwnProperty("payloadUrl")) {
      object.payloadUrl = ApiClient.convertToType(data["payloadUrl"], "String");
    }

    return object;
  }

  /**
   * @return { module:model/WebhookData.EventEnum }
   */
  getEvent() {
    return this.event;
  }

  /**
   * @param { module:model/WebhookData.EventEnum } event
   */
  setEvent(event) {
    this.event = event;
  }
  /**
   * @return { String }
   */
  getOrganization() {
    return this.organization;
  }

  /**
   * @param { String } organization
   */
  setOrganization(organization) {
    this.organization = organization;
  }
  /**
   * @return { String }
   */
  getPayloadUrl() {
    return this.payloadUrl;
  }

  /**
   * @param { String } payloadUrl
   */
  setPayloadUrl(payloadUrl) {
    this.payloadUrl = payloadUrl;
  }

  /**
   * Allowed values for the "event" property.
   * @enum { String }
   */
  static EventEnum = {
    /**
     * value: "operationCreated"
     * @const
     * @readonly
     */
    operationCreated: "operationCreated",
    /**
     * value: "operationStateChanged"
     * @const
     * @readonly
     */
    operationStateChanged: "operationStateChanged",
    /**
     * value: "reportCreated"
     * @const
     * @readonly
     */
    reportCreated: "reportCreated",
    /**
     * value: "reportStateChanged"
     * @const
     * @readonly
     */
    reportStateChanged: "reportStateChanged"
  };
}
