/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.23.2
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Feedback } from '../model/feedback';
import { ImageData } from '../model/imageData';
import { Operation } from '../model/operation';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { ImageServiceInterface }                            from './image.serviceInterface';


@Injectable()
export class ImageService implements ImageServiceInterface {

    protected basePath = 'https://api.keyclic.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Remove one Image resource.
     * 
     * @param xKeyclicApp 
     * @param operation The identifier of the resource formatted as GUID string.
     * @param image The identifier of the resource formatted as GUID string.
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteImageByOperationAndImage(xKeyclicApp: string, operation: string, image: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteImageByOperationAndImage(xKeyclicApp: string, operation: string, image: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteImageByOperationAndImage(xKeyclicApp: string, operation: string, image: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteImageByOperationAndImage(xKeyclicApp: string, operation: string, image: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling deleteImageByOperationAndImage.');
        }
        if (operation === null || operation === undefined) {
            throw new Error('Required parameter operation was null or undefined when calling deleteImageByOperationAndImage.');
        }
        if (image === null || image === undefined) {
            throw new Error('Required parameter image was null or undefined when calling deleteImageByOperationAndImage.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/operations/${encodeURIComponent(String(operation))}/images/${encodeURIComponent(String(image))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one Image resource.
     * 
     * @param xKeyclicApp 
     * @param feedback The identifier of the resource formatted as GUID string.
     * @param image The identifier of the resource formatted as GUID string.
     * @param width 
     * @param height 
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getImageByFeedbackAndImageAndWidthAndHeight(xKeyclicApp: string, feedback: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public getImageByFeedbackAndImageAndWidthAndHeight(xKeyclicApp: string, feedback: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public getImageByFeedbackAndImageAndWidthAndHeight(xKeyclicApp: string, feedback: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public getImageByFeedbackAndImageAndWidthAndHeight(xKeyclicApp: string, feedback: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling getImageByFeedbackAndImageAndWidthAndHeight.');
        }
        if (feedback === null || feedback === undefined) {
            throw new Error('Required parameter feedback was null or undefined when calling getImageByFeedbackAndImageAndWidthAndHeight.');
        }
        if (image === null || image === undefined) {
            throw new Error('Required parameter image was null or undefined when calling getImageByFeedbackAndImageAndWidthAndHeight.');
        }
        if (width === null || width === undefined) {
            throw new Error('Required parameter width was null or undefined when calling getImageByFeedbackAndImageAndWidthAndHeight.');
        }
        if (height === null || height === undefined) {
            throw new Error('Required parameter height was null or undefined when calling getImageByFeedbackAndImageAndWidthAndHeight.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];

        return this.httpClient.get(`${this.basePath}/feedbacks/${encodeURIComponent(String(feedback))}/images/${encodeURIComponent(String(image))}/${encodeURIComponent(String(width))}/${encodeURIComponent(String(height))}`,
            {
                responseType: "blob",
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one Image resource.
     * 
     * @param xKeyclicApp 
     * @param operation The identifier of the resource formatted as GUID string.
     * @param image The identifier of the resource formatted as GUID string.
     * @param width 
     * @param height 
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getImageByOperationAndImageAndWidthAndHeight(xKeyclicApp: string, operation: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public getImageByOperationAndImageAndWidthAndHeight(xKeyclicApp: string, operation: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public getImageByOperationAndImageAndWidthAndHeight(xKeyclicApp: string, operation: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public getImageByOperationAndImageAndWidthAndHeight(xKeyclicApp: string, operation: string, image: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling getImageByOperationAndImageAndWidthAndHeight.');
        }
        if (operation === null || operation === undefined) {
            throw new Error('Required parameter operation was null or undefined when calling getImageByOperationAndImageAndWidthAndHeight.');
        }
        if (image === null || image === undefined) {
            throw new Error('Required parameter image was null or undefined when calling getImageByOperationAndImageAndWidthAndHeight.');
        }
        if (width === null || width === undefined) {
            throw new Error('Required parameter width was null or undefined when calling getImageByOperationAndImageAndWidthAndHeight.');
        }
        if (height === null || height === undefined) {
            throw new Error('Required parameter height was null or undefined when calling getImageByOperationAndImageAndWidthAndHeight.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];

        return this.httpClient.get(`${this.basePath}/operations/${encodeURIComponent(String(operation))}/images/${encodeURIComponent(String(image))}/${encodeURIComponent(String(width))}/${encodeURIComponent(String(height))}`,
            {
                responseType: "blob",
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one Image resource.
     * 
     * @param xKeyclicApp 
     * @param person The identifier of the resource formatted as GUID string.
     * @param width 
     * @param height 
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getImageByPersonAndWidthAndHeight(xKeyclicApp: string, person: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public getImageByPersonAndWidthAndHeight(xKeyclicApp: string, person: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public getImageByPersonAndWidthAndHeight(xKeyclicApp: string, person: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public getImageByPersonAndWidthAndHeight(xKeyclicApp: string, person: string, width: string, height: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling getImageByPersonAndWidthAndHeight.');
        }
        if (person === null || person === undefined) {
            throw new Error('Required parameter person was null or undefined when calling getImageByPersonAndWidthAndHeight.');
        }
        if (width === null || width === undefined) {
            throw new Error('Required parameter width was null or undefined when calling getImageByPersonAndWidthAndHeight.');
        }
        if (height === null || height === undefined) {
            throw new Error('Required parameter height was null or undefined when calling getImageByPersonAndWidthAndHeight.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];

        return this.httpClient.get(`${this.basePath}/people/${encodeURIComponent(String(person))}/image/${encodeURIComponent(String(width))}/${encodeURIComponent(String(height))}`,
            {
                responseType: "blob",
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create one Image resource.
     * 
     * @param xKeyclicApp 
     * @param feedback The identifier of the resource formatted as GUID string.
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param imageData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postImageByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe?: 'body', reportProgress?: boolean): Observable<Feedback>;
    public postImageByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Feedback>>;
    public postImageByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Feedback>>;
    public postImageByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling postImageByFeedback.');
        }
        if (feedback === null || feedback === undefined) {
            throw new Error('Required parameter feedback was null or undefined when calling postImageByFeedback.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Feedback>(`${this.basePath}/feedbacks/${encodeURIComponent(String(feedback))}/images`,
            imageData,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create one Image resource.
     * 
     * @param xKeyclicApp 
     * @param operation The identifier of the resource formatted as GUID string.
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param imageData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postImageByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe?: 'body', reportProgress?: boolean): Observable<Operation>;
    public postImageByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operation>>;
    public postImageByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operation>>;
    public postImageByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, imageData?: ImageData, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling postImageByOperation.');
        }
        if (operation === null || operation === undefined) {
            throw new Error('Required parameter operation was null or undefined when calling postImageByOperation.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Operation>(`${this.basePath}/operations/${encodeURIComponent(String(operation))}/images`,
            imageData,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
