/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.23.2
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Person } from '../model/person';
import { PersonPagination } from '../model/personPagination';
import { PersonPatch } from '../model/personPatch';


import { Configuration }                                     from '../configuration';


export interface PersonServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Retrieve all Person resources.
    * 
    * @param xKeyclicApp 
    * @param acceptLanguage 
    * @param xKeyclicAppVersion 
    * @param page Page of the overview.
    * @param limit Page of the overview.
    * @param order 
    * @param after 
    * @param before 
    * @param searchFamilyName 
    * @param searchGivenName 
    * @param searchJobTitle 
    * @param searchUsername 
    * @param searchEmail 
    */
    cgetPeople(xKeyclicApp: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, page?: number, limit?: number, order?: 'asc' | 'desc', after?: Date, before?: Date, searchFamilyName?: string, searchGivenName?: string, searchJobTitle?: string, searchUsername?: string, searchEmail?: string, extraHttpRequestParams?: any): Observable<PersonPagination>;

    /**
    * Retrieve one Person resource.
    * 
    * @param xKeyclicApp 
    * @param person The identifier of the resource formatted as GUID string.
    * @param acceptLanguage 
    * @param xKeyclicAppVersion 
    */
    getPerson(xKeyclicApp: string, person: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, extraHttpRequestParams?: any): Observable<Person>;

    /**
    * Edit one Person resource.
    * 
    * @param xKeyclicApp 
    * @param person The identifier of the resource formatted as GUID string.
    * @param acceptLanguage 
    * @param xKeyclicAppVersion 
    * @param personPatch 
    */
    patchPerson(xKeyclicApp: string, person: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, personPatch?: PersonPatch, extraHttpRequestParams?: any): Observable<Person>;

}
