/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.23.2
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Organization } from '../model/organization';
import { OrganizationPagination } from '../model/organizationPagination';
import { RelationshipData } from '../model/relationshipData';


import { Configuration }                                     from '../configuration';


export interface RelationshipServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Retrieve all Relationship resources.
    * 
    * @param xKeyclicApp 
    * @param organization The identifier of the resource formatted as GUID string.
    * @param acceptLanguage 
    * @param xKeyclicAppVersion 
    * @param businessActivity The identifier of the resource formatted as GUID string.
    * @param geoCoordinates One latitude and one longitude serialized and separated by a plus or a minus sign.
    * @param geoPoint One latitude and one longitude serialized and separated by a plus or a minus sign.
    * @param page Page of the overview.
    * @param limit Page of the overview.
    * @param order 
    * @param after 
    * @param before 
    * @param searchName 
    * @param searchAlternateName 
    * @param searchDescription 
    * @param searchBillingEmailAddress 
    * @param searchNotificationEmailAddress 
    */
    cgetRelationshipsByOrganization(xKeyclicApp: string, organization: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, businessActivity?: string, geoCoordinates?: string, geoPoint?: string, page?: number, limit?: number, order?: 'asc' | 'desc', after?: Date, before?: Date, searchName?: string, searchAlternateName?: string, searchDescription?: string, searchBillingEmailAddress?: string, searchNotificationEmailAddress?: string, extraHttpRequestParams?: any): Observable<OrganizationPagination>;

    /**
    * Remove one Relationship resource.
    * 
    * @param xKeyclicApp 
    * @param organization The identifier of the resource formatted as GUID string.
    * @param relationship The identifier of the resource formatted as GUID string.
    * @param acceptLanguage 
    * @param xKeyclicAppVersion 
    */
    deleteRelationshipByOrganizationAndRelationship(xKeyclicApp: string, organization: string, relationship: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Create one Relationship resource.
    * 
    * @param xKeyclicApp 
    * @param organization The identifier of the resource formatted as GUID string.
    * @param acceptLanguage 
    * @param xKeyclicAppVersion 
    * @param relationshipData 
    */
    postRelationshipByOrganization(xKeyclicApp: string, organization: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, relationshipData?: RelationshipData, extraHttpRequestParams?: any): Observable<Organization>;

}
