/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.23.2
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Tracking } from '../model/tracking';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { TrackingServiceInterface }                            from './tracking.serviceInterface';


@Injectable()
export class TrackingService implements TrackingServiceInterface {

    protected basePath = 'https://api.keyclic.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Retrieve one Tracking resource.
     * 
     * @param xKeyclicApp 
     * @param feedback The identifier of the resource formatted as GUID string.
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTrackingByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'body', reportProgress?: boolean): Observable<Tracking>;
    public getTrackingByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tracking>>;
    public getTrackingByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tracking>>;
    public getTrackingByFeedback(xKeyclicApp: string, feedback: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling getTrackingByFeedback.');
        }
        if (feedback === null || feedback === undefined) {
            throw new Error('Required parameter feedback was null or undefined when calling getTrackingByFeedback.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];

        return this.httpClient.get<Tracking>(`${this.basePath}/feedbacks/${encodeURIComponent(String(feedback))}/tracking`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one Tracking resource.
     * 
     * @param xKeyclicApp 
     * @param operation The identifier of the resource formatted as GUID string.
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTrackingByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'body', reportProgress?: boolean): Observable<Tracking>;
    public getTrackingByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tracking>>;
    public getTrackingByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tracking>>;
    public getTrackingByOperation(xKeyclicApp: string, operation: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling getTrackingByOperation.');
        }
        if (operation === null || operation === undefined) {
            throw new Error('Required parameter operation was null or undefined when calling getTrackingByOperation.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];

        return this.httpClient.get<Tracking>(`${this.basePath}/operations/${encodeURIComponent(String(operation))}/tracking`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one Tracking resource.
     * 
     * @param xKeyclicApp 
     * @param report The identifier of the resource formatted as GUID string.
     * @param acceptLanguage 
     * @param xKeyclicAppVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTrackingByReport(xKeyclicApp: string, report: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'body', reportProgress?: boolean): Observable<Tracking>;
    public getTrackingByReport(xKeyclicApp: string, report: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tracking>>;
    public getTrackingByReport(xKeyclicApp: string, report: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tracking>>;
    public getTrackingByReport(xKeyclicApp: string, report: string, acceptLanguage?: 'fr-FR' | 'en-US', xKeyclicAppVersion?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (xKeyclicApp === null || xKeyclicApp === undefined) {
            throw new Error('Required parameter xKeyclicApp was null or undefined when calling getTrackingByReport.');
        }
        if (report === null || report === undefined) {
            throw new Error('Required parameter report was null or undefined when calling getTrackingByReport.');
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('accept-language', String(acceptLanguage));
        }
        if (xKeyclicApp !== undefined && xKeyclicApp !== null) {
            headers = headers.set('x-keyclic-app', String(xKeyclicApp));
        }
        if (xKeyclicAppVersion !== undefined && xKeyclicAppVersion !== null) {
            headers = headers.set('x-keyclic-app-version', String(xKeyclicAppVersion));
        }

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/hal+json;charset=UTF-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=UTF-8'
        ];

        return this.httpClient.get<Tracking>(`${this.basePath}/reports/${encodeURIComponent(String(report))}/tracking`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
