/**
 * Keyclic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.23.2
 * Contact: techies@keyclic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeedbackEmbedded } from './feedbackEmbedded';
import { FeedbackGeoCoordinates } from './feedbackGeoCoordinates';
import { FeedbackLinks } from './feedbackLinks';


export interface Feedback { 
    description?: string;
    geoCoordinates: FeedbackGeoCoordinates;
    metadata?: Array<string>;
    id: string;
    createdAt?: Date;
    readonly type?: string;
    readonly _public?: boolean;
    readonly state?: Array<string>;
    links?: FeedbackLinks;
    embedded?: FeedbackEmbedded;
}
