name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-dart:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{secrets.PUB_AUTH_ACCESS_TOKEN}}",
            "refreshToken":"${{secrets.DART_AUTH_REFRESH_TOKEN}}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1570721159347
          }
          EOF
      - name: Print infos
        run: |
          set -x
          whoami
          echo $PATH
          pwd
          ls -la
      - name: Publish package
        run: pub publish -f
